services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - data_dev:/app/data
      - ./app:/app/app
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=canviar-a-una-clau-segura-en-produccio
      - DATABASE_URL=sqlite:////app/data/pinyator_dev.db

volumes:
  data_dev:
